name: shared_asr_utils
description: Speech-recognition related classes. Used by the sherpa_onnx_dart package.
version: 0.0.1
repository: https://github.com/nmfisher/shared_asr_utils

environment:
  sdk: ^3.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
