name: shared_asr_utils_dart
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/nmfisher/shared_asr_utils_dart

environment:
  sdk: ^3.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
